---
- hosts: deb
  vars_files:
    - vars/deb.yml
  gather_facts: no
  remote_user: devops
  become: true

  tasks:
  - include: tasks/set-up-web-server.yml
  handlers:
  - include: handlers/restart-apache.yml

- hosts: rpm
  vars_files:
    - vars/rpm.yml
  gather_facts: no
  remote_user: devops
  become: true

  tasks:
  - include: tasks/set-up-web-server.yml

  handlers:
  - include: handlers/restart-apache.yml
