---

# File ./tasks/install-packages.yml

- name: Install packages for both RPM-based and DEB-based servers
  ansible.builtin.package:
    name: "{{ apache }}"
    state: latest
- name: Enalbe the damn service and start it
  ansible.buildin.service:
    name: "{{ apache }}"
    enabled: yes
    state: started
