---

# File ./tasks/install-packages.yml

- name: Install packages for both RPM-based and DEB-based servers
  ansible.builtin.package:
    name: "{{ apache }}"
    state: latest

- name: Enable the service and start it
  ansible.builtin.service:
    name: "{{ apache }}"
    enabled: yes
    state: started
