---
- name: Create document root
  file:
    path: "/var/www/{{ http_host }}"
    state: directory
    owner: "{{ app_user }}"
    mode: '0755'

- name: Copy index test page
  template:
    src: "files/index.html.j2"
    dest: "/var/www/{{ http_host }}/index.html"

- name: Set up Apache virtualHost
  template:
    src: "files/apache.conf.j2"
    dest: "{{ conf_path }}"
  notify: Restart Apache
